# Generated by Django 5.2.6 on 2025-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('accessories', 'Accessories')], default='shoes', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
    ]
